# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 20:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
                ('cleared', models.BooleanField(default=False)),
                ('amount_paid', models.FloatField()),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('location', models.CharField(max_length=200)),
                ('rent_price', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('bedrooms', models.IntegerField()),
                ('description', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('managed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HouseGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='uploads')),
                ('image2', models.ImageField(upload_to='uploads')),
                ('image3', models.ImageField(upload_to='uploads')),
                ('image4', models.ImageField(upload_to='uploads')),
                ('image5', models.ImageField(upload_to='uploads')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarthouse.House')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=13)),
                ('amount', models.FloatField()),
                ('status', models.CharField(max_length=32)),
                ('payment_type', models.CharField(choices=[('Rent', 'Rent'), ('Purchase', 'Purchase')], default='Rent', max_length=20)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarthouse.House')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarthouse.House'),
        ),
    ]
