# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
