# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthouse', '0002_house_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='primary_img',
            field=models.ImageField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='housegallery',
            name='image1',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='housegallery',
            name='image2',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='housegallery',
            name='image3',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='housegallery',
            name='image4',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='housegallery',
            name='image5',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
