# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthouse', '0005_house_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housegallery',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='housegallery',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='housegallery',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='housegallery',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='housegallery',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
