# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-07 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smarthouse', '0006_auto_20171204_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
