# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-17 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthouse', '0009_auto_20171230_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ('-is_available', '-date_posted')},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-date_paid',)},
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_by',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
